# Generated by Django 5.0.1 on 2024-02-06 09:08

import courses.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='courses_previews', validators=[courses.validators.course_preview_validate], verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursecategory', verbose_name='Категория'),
        ),
    ]
