# Generated by Django 5.0.1 on 2024-02-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default=None, max_length=255, verbose_name='Заголовок'),
        ),
    ]
