# Generated by Django 5.0.1 on 2024-02-13 08:55

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_note_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('photo', models.ImageField(upload_to='awards_photos', validators=[courses.validators.award_image_validate], verbose_name='Значок')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='awards',
            field=models.ManyToManyField(to='courses.award', verbose_name='Достижения'),
        ),
    ]
