# Generated by Django 5.0.1 on 2024-02-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_award_customuser_awards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='award',
            name='desc',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
